### ISSUE TITLE
Error parsing the plugin name from processed template

### ISSUE THREAD

**Issue by ahmetb** [rajatjindal/krew-release-bot#63]
I'm getting an error like:
```
...
time="2022-08-29T21:16:48Z" level=info msg="downloaded file /tmp/768358419/1661807808"
time="2022-08-29T21:16:48Z" level=fatal msg="failed to get plugin name from processed template.
err: error converting YAML to JSON: yaml: line 19: did not find expected '-' indicator"
```

I'm using `rajatjindal/krew-release-bot@v0.0.43` action.

My template looks like the following:

```yaml
apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: foreach
spec:
  version: {{ .TagName }}
  homepage: https://github.com/ahmetb/kubectl-foreach
  shortDescription: Run kubectl commands against some/all contexts in parallel
  description: |
    Lets you run the same kubectl command against multiple contexts
    simultaneously and prints their output, prefixed by context name.
    You can choose or exclude contexts with exact name match or regular
    expression patterns.
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/ahmetb/kubectl-foreach/releases/download/{{ .TagName }}/kubectl-foreach_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
      bin: kubectl-foreach
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      {{addURIAndSha "https://github.com/ahmetb/kubectl-foreach/releases/download/{{ .TagName }}/kubectl-foreach_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
      bin: kubectl-foreach
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/ahmetb/kubectl-foreach/releases/download/{{ .TagName }}/kubectl-foreach_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
      bin: kubectl-foreach
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      {{addURIAndSha "https://github.com/ahmetb/kubectl-foreach/releases/download/{{ .TagName }}/kubectl-foreach_{{ .TagName }}_linux_arm64.tar.gz" .TagName }}
      bin: kubectl-foreach
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      {{addURIAndSha "https://github.com/ahmetb/kubectl-foreach/releases/download/{{ .TagName }}/kubectl-foreach_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
      bin: kubectl-foreach.exe

```
