### ISSUE TITLE
Krew GITHUB_REF failure

### ISSUE THREAD

**Issue by AlexsJones** [rajatjindal/krew-release-bot#79]
Hello, recently we have noticed in the K8sGPT release pipeline a new type of error from krew.
https://github.com/k8sgpt-ai/k8sgpt/actions/runs/11763964917/job/32768577152

To my knowledge we have not changed anything:

Error 
```
Digest: sha256:cb2a5cd92097ac4a92846833d7a9340d20ed247435fa447ccd3fef5499c65793
Status: Downloaded newer image for ghcr.io/rajatjindal/krew-release-bot:v0.0.46
time="2024-11-10T09:47:19Z" level=fatal msg="GITHUB_REF expected to be of format refs/tags/<tag> but found \"refs/heads/main\""
```

The ref is correct as we are releasing the main branch on a merge of the goreleaser PR set. 

Here is the .krew.yaml:
```
apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: gpt
spec:
  version: {{ .TagName }}
  homepage: https://github.com/k8sgpt-ai/k8sgpt
  shortDescription: "Giving Kubernetes Superpowers to everyone"
  description: |
    A tool for scanning your Kubernetes clusters, diagnosing, and triaging issues in simple English.
  platforms:
    ##########
    # Darwin #
    ##########
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/k8sgpt-ai/k8sgpt/releases/download/{{ .TagName }}/k8sgpt_Darwin_x86_64.tar.gz" .TagName | indent 6 }}
      files:
        - from: "k8sgpt"
          to: "kubectl-gpt"
        - from: "LICENSE"
          to: "."
      bin: kubectl-gpt
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      {{addURIAndSha "https://github.com/k8sgpt-ai/k8sgpt/releases/download/{{ .TagName }}/k8sgpt_Darwin_arm64.tar.gz" .TagName | indent 6 }}
      files:
        - from: "k8sgpt"
          to: "kubectl-gpt"
        - from: "LICENSE"
          to: "."
      bin: kubectl-gpt

    #########
    # Linux #
    #########
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/k8sgpt-ai/k8sgpt/releases/download/{{ .TagName }}/k8sgpt_Linux_x86_64.tar.gz" .TagName | indent 6 }}
      files:
        - from: "k8sgpt"
          to: "kubectl-gpt"
        - from: "LICENSE"
          to: "."
      bin: kubectl-gpt
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      {{addURIAndSha "https://github.com/k8sgpt-ai/k8sgpt/releases/download/{{ .TagName }}/k8sgpt_Linux_arm64.tar.gz" .TagName | indent 6 }}
      files:
        - from: "k8sgpt"
          to: "kubectl-gpt"
        - from: "LICENSE"
          to: "."
      bin: kubectl-gpt
    - selector:
        matchLabels:
          os: linux
          arch: "386"
      {{addURIAndSha "https://github.com/k8sgpt-ai/k8sgpt/releases/download/{{ .TagName }}/k8sgpt_Linux_i386.tar.gz" .TagName | indent 6 }}
      files:
        - from: "k8sgpt"
          to: "kubectl-gpt"
        - from: "LICENSE"
          to: "."
      bin: kubectl-gpt

    ###########
    # Windows #
    ###########
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      {{addURIAndSha "https://github.com/k8sgpt-ai/k8sgpt/releases/download/{{ .TagName }}/k8sgpt_Windows_x86_64.zip" .TagName | indent 6 }}
      files:
        - from: "k8sgpt"
          to: "kubectl-gpt"
        - from: "LICENSE"
          to: "."
      bin: kubectl-gpt
    - selector:
        matchLabels:
          os: windows
          arch: arm64
      {{addURIAndSha "https://github.com/k8sgpt-ai/k8sgpt/releases/download/{{ .TagName }}/k8sgpt_Windows_arm64.zip" .TagName | indent 6 }}
      files:
        - from: "k8sgpt"
          to: "kubectl-gpt"
        - from: "LICENSE"
          to: "."
      bin: kubectl-gpt
    - selector:
        matchLabels:
          os: windows
          arch: "386"
      {{addURIAndSha "https://github.com/k8sgpt-ai/k8sgpt/releases/download/{{ .TagName }}/k8sgpt_Windows_i386.zip" .TagName | indent 6 }}
      files:
        - from: "k8sgpt"
          to: "kubectl-gpt"
        - from: "LICENSE"
          to: "."
      bin: kubectl-gpt
```

Help appreciated!
